### PR TITLE
Added section on coding standard.

### PR DESCRIPTION
**Pull request by sgpinkus**
Pretty brief but better than nothing for now/

### CODE REVIEW

**Comment by bebehei** [comment]
Thanks for the patch!

**Comment by myrdd** [comment]
@bebehei you've reverted my changes by merging this PR.

@sam-at-github what's the default tabsize? Eight, no? I think it should be mentioned.

**Comment by sgpinkus** [comment]
> what's the default tabsize? Eight, no? I think it should be mentioned. 

Doe that matter? Isn't that the whole point in using tabs? Add if you want though.

**Comment by bebehei** [comment]
> @bebehei you've reverted my changes by merging this PR.

That's called trust ;-) I did not review the changes. Sorry.

> @sam-at-github what's the default tabsize? Eight, no? I think it should be mentioned.

You don't need to mention the tab-size, if every indentation is a tab.

**Comment by myrdd** [comment]
I was referring to

> - The soft line length limited should be 80 characters

What's a _soft line length_? In my understanding, if the limit is 80 characters, a tab character has to be "mapped" to a certain amount of equivalent "spaces" in order to know where the 80-character limit is. — please clarify, I could not find an answer by searching the web.

**Comment by bebehei** [comment]
That's a good objection! At that point, I would use the already-defined one in rsnapshot-program.pl:

> # in vi, do: set ts=4 sw=4

**Comment by sgpinkus** [comment]
Soft limit === its not a hard rule. I can't remember where I picked that up. Some project was using it.

**Comment by sgpinkus** [comment]
Oh wait - http://www.php-fig.org/psr/psr-2/:

> There MUST NOT be a hard limit on line length; the soft limit MUST be 120 characters; lines SHOULD be 80 characters or less.

Don't hate just coz its PHP:)

**Comment by myrdd** [comment]
Okay, so "0-80 characters" is ok, no?
see http://stackoverflow.com/questions/14962667/what-is-a-line-length-soft-limit-and-how-do-i-interpret-this-in-the-psr-2-conv

I think `1 tab == 4 "characters"` is good.

**Comment by sgpinkus** [comment]
> In my understanding, if the limit is 80 characters, a tab character has to be "mapped" to a certain amount of equivalent "spaces" in order to know where the 80-character limit is. — please clarify, I could not find an answer by searching the web.

Oh I see now. Yeah maybe worth mentioning tab == 4 characters. Inline with existing code and PSR :).

> Okay, so "0-80 characters" is ok, no?
> see http://stackoverflow.com/questions/14962667/what-is-a-line-length-soft-limit-and-how-do-i-interpret-this-in-the-psr-2-conv

Never really thought about it too hard, but the top rated answer on that github post coincides with my interpretation of PSR-2.

**Pull request merged**
